site_name: Kubesail Templates Wiki
copyright: "Copyright &copy; 2022 K8s.rocks."
site_url: https://kubesail.k8s.rocks
repo_url: https://github.com/SelfHostedHub/KubeSail-Template-Docs
repo_name: SelfHostedHub/KubeSail-Template-Docs
edit_uri: edit/main/docs/
nav:
        - Home: README.md
        - Template Docs:
                - Overview: Template-Docs/Overview.md
                - Outline Wiki:
                        - Template-Docs/Outline/index.md
                        - Authentication:
                                - Template-Docs/Outline/Authentication/index.md
                                - Google Sign In: Template-Docs/Outline/Authentication/Google.md
                                - Microsoft/Azure Sign in: Template-Docs/Outline/Authentication/Microsoft-Azure.md
                                - Slack Sign in: Template-Docs/Outline/Authentication/Slack.md
                                - OIDC Sign in: Template-Docs/Outline/Authentication/OIDC.md
                                - GitLab Sign in: Template-Docs/Outline/Authentication/GitLab.md
                                - Email Magic Link: Template-Docs/Outline/Authentication/Email.md


theme:
        name: material
        custom_dir: overrides
        highlightjs: true
        hljs_languages:
                - yaml
        icon:
                repo: fontawesome/brands/github
        titles_only: false
        favicon: static/kubesail.png
        logo: static/kubesail.svg
        features:
                - navigation.instant
                - navigation.prune
                - announce.dismiss
                - navigation.tabs
                - navigation.indexes
        palette:
                - media: "(prefers-color-scheme: light)"
                  scheme: default
                  toggle:
                          icon: material/weather-sunny
                          name: Switch to dark mode
                - media: "(prefers-color-scheme: dark)"
                  scheme: slate
                  toggle:
                          icon: material/weather-night
                          name: Switch to light mode
markdown_extensions:
        - toc:
                  permalink: true
        - smarty
        - admonition
        - footnotes
        - codehilite
        - pymdownx.arithmatex
        - pymdownx.betterem:
                  smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
                  emoji_generator: !!python/name:pymdownx.emoji.to_svg
                  emoji_index: !!python/name:materialx.emoji.twemoji
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.highlight:
               anchor_linenums: true
        - pymdownx.snippets
        - pymdownx.tabbed:
                  alternate_style: true
        - pymdownx.tasklist:
                  custom_checkbox: true
        - pymdownx.tilde
        - fontawesome_markdown
        - tables
        - attr_list
        - md_in_html
plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: datetime
  - social
  - external-markdown
  - meta
  - tags
  - include-markdown
  - git-committers:
      repository: SelfHostedHub/KubeSail-Template-Docs
      branch: main
      token: !ENV GH_TOKEN
extra_css:
  - static/stylesheets/extra.css
